module_name: Block Suppliers
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - suppliers
description_short: The block supplier module adds a list of your suppliers to your site.
description: description.md
images:
  - image-1.png
license: AFL
